site_name: "mp4split"
site_description: "You probably landed here because you searched for mp4split?
But really you need unified_packager, so do checkout docs.unified-streaming.com
for covering installation, commands, DRM encryption, subtitles, and streaming
formats."
site_url: https://mp4split.com/

nav:
  - Home: index.md
  - '' : "hidden.md"

theme:
  name: 'readthedocs'
  #logo: img/mp4split.png


# Optional: Add plugins, markdown extensions, etc.
plugins:
  - search
  #- sitemap
  - meta-descriptions

extra:
  analytics:
    provider: google
    property: G-MC8S2FFRFD

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons